### ISSUE TITLE
Extra text on album page in library 

### ISSUE THREAD

**Issue by cflynn90** [RudeySH/lastfm-bulk-edit#46] opened 2024-09-29 01:01 UTC
With script enabled, I get a "No Album" text red in under the artist name on my Library Albums page.

With script enabled:
![image](https://github.com/user-attachments/assets/9c75762b-5d4a-40ff-a59b-12f349523eaa)

Without script enabled:
![image](https://github.com/user-attachments/assets/fa329a36-0f0d-4d5a-87eb-50d63958f54a)

**Comment by RudeySH** [comment] 2024-09-30 07:47
This is a duplicate of issue #45 and this was fixed 2 weeks ago. You should update the script to the latest version. To do so, simply step 3 of the [instructions](https://github.com/RudeySH/lastfm-bulk-edit?tab=readme-ov-file#instructions) again.

**Closed by RudeySH** 2024-09-30 07:47 UTC
